### ISSUE TITLE
plain website

### ISSUE THREAD

**Issue by lolBoi9696** [ImajinDevon/ImajinDevon.github.io#1]
fixxxxxx

**Comment by ImajinDevon** [comment]
how do i block someone on github

**Comment by lolBoi9696** [comment]
wait im sorry dont block me lol

**Comment by lolBoi9696** [comment]
also i dont think you can ?

**Comment by LMBishop** [comment]
https://github.com/settings/blocked_users

:)

**Comment by lolBoi9696** [comment]
> https://github.com/settings/blocked_users
> 
> :)

no dont tell him
